#!/usr/bin/bash
if [ "$TRAVIS_PULL_REQUEST" -eq 'false' ]; then
  if [ "$TRAVIS_BRANCH" -eq  'master' ] ||  [ "$TRAVIS_BRANCH" -eq 'develop' ]; then
    openssl aes-256-cbc -K $encrypted_040459e821a3_key -iv $encrypted_040459e821a3_iv -in .travis/codesigning.asc.enc -out .travis/codesigning.asc -d
    gpg --fast-import .travis/codesigning.asc
  fi
fi
